requesttxt: "You have reveived an autograph request from %PLAYER%!"
requestsenttxt: "Your request to %PLAYER% has been sent!"
requestexpiredtxt: "Your request to %PLAYER% has expired!"
requestfilledtxt: "%PLAYER% has signed you book! Go check their signature out!"
requestalreadyrunningtxt: "That player already has a sign request pending! Please wait for that request to be either filled or exipre!"
signconfirmtxt: "You have succesfully signed %PLAYER%'s autograph book!"
accepttxt: "%PLAYER% has accepted your autograph request! Send a message using /sm!"
denytxt: "%PLAYER% has denied your autograph request! :("
countdowntxt: "Your autograph request to %PLAYER% expires in %TIME% second(s)!"
norequeststxt: "You currently don't have any requests pending!"
nothingtosigntxt: "You currently don't have any books available to sign!"
#In seconds
requesttime: 20

book-name: "Autograph Book"
book-slot: 0

do-prefix: true

#Set if a book will always be given on server join, or if we first check if the player already has a book
always-give-on-join: false

