requesttxt: "You have reveived an autograph request from %PLAYER%!"
requestsenttxt: "Your request to %PLAYER% has been sent!"
requestexpiredtxt: "Your request to %PLAYER% has expired!"
accepttxt: "%PLAYER% has accepted your autograph request! Send a message using /sm!"
denytxt: "%PLAYER% has denied your autograph request! :("
countdowntxt: "Your autograph request to %PLAYER% expires in %TIME% second(s)!"
norequeststxt: "You currently don't have any requests running!"
#In seconds
requesttime: 20

# A list of alliases for the autograph command
aliasses:
  - a
  - acceptsign

book-name: "Autograph Book"
