requesttxt: "You have reveived an autograph request from %PLAYER%!"
requestsenttxt: "Your request to %PLAYER% has been sent!"
requestexpiredtxt: "Your request to %PLAYER% has expired!"
requestfilledtxt: "%PLAYER% has signed you book! Go check their signature out!"
signconfirmtxt: "You have succesfully signed %PLAYER%'s autograph book!"
accepttxt: "%PLAYER% has accepted your autograph request! Send a message using /sm!"
denytxt: "%PLAYER% has denied your autograph request! :("
countdowntxt: "Your autograph request to %PLAYER% expires in %TIME% second(s)!"
norequeststxt: "You currently don't have any requests pending!"
nothingtosigntxt: "You currently don't have any books available to sign!"
#In seconds
requesttime: 20

# A list of alliases for the autograph command
aliases:
  - a
  - acceptsign

book-name: "Autograph Book"

do-prefix: true
