main: com.koens.autograph.Autograph
author: TheRealKS123
name: Autograph
version: 1.1.0
commands:
  autograph:
    description: accept a sign request
    usage: /autograph <accept> |deny|sign<msg>|request<IGN>
  a:
    description: accept a sign request
    usage: /autograph <accept> |deny|sign<msg>|request<IGN>
  sign:
    description: accept a sign request
    usage: /autograph <accept> |deny|sign<msg>|request<IGN>
  signature:
    description: accept a sign request
    usage: /autograph <accept> |deny|sign<msg>|request<IGN>
  ainfo:
    description: display info about the plugin
    usage: /ainfo
  autographinfo:
    description: display info about the plugin
    usage: /ainfo
permissions:
  autograph.*:
    description: Gives access to all autograph commands
    children:
      autograph.accept: true
      autograph.deny: true
      autograph.request: true
      autograph.sign: true
  autograph.accept:
    description: allows you to accept an autograph request
    default: true
  autograph.deny:
    description: allows you to deny an autograph request
    default: true
  autograph.request:
    description: Gives access to autograph requesting
    default: true
  autograph.sign:
   description: allows you to request and sign autograph books
   default: true
   children:
     autograph.request: true